### ISSUE TITLE
SQL Optimisation : implicit join of identity of some related object should only join when FK not present

### ISSUE THREAD

**Issue by andyjefferson** [datanucleus/datanucleus-rdbms#161]
If we have a candidate class MyClass with 1-1 relation to RelatedClass and we make reference to
cand.related.id
then this should only join when the FK is at the other side, or if the "id" is a persistent object.
This will reduce the number of joins in that specific situation

**Comment by beikov** [comment]
This is especially important because currently using the id in the ON clause of a join leads to new join being added and the alias of that join being used in the ON clause, but now the join nodes have circular dependencies leading to SQL errors. In the special case that a join of a relation which uses a collection table also makes use of collection table attributes in the ON clause, you might even want to generate a derived table reference a.k.a. a subquery in the from clause.
