### ISSUE TITLE
Java byte-array is mapped to "varbinary(1)" in ms sqlserver

### ISSUE THREAD

**Issue by nbartels** [datanucleus/datanucleus-rdbms#324]
I wrote a simple test case to show the problem: https://github.com/nbartels/test-jdo/tree/varbinary-bug

First you need a microsoft sqlserver. I found the problem with version 14.00.2027.

The "Person" object of the testcase is extended with an additional `byte array` field called `someByteData`.

While running the unit test, the table is created in the database, but the column uses the type varbinary(1). The varbinary itself is not the problem, the problem is the size. The provided data cannot be stored in the field and I get this exception:
```
java.sql.BatchUpdateException: String or binary data would be truncated.
```

In the database the column looks like on the screenshot.
![mssql-bytearray-varbinary](https://user-images.githubusercontent.com/1113969/66207937-52d98680-e6b4-11e9-8549-e77be2769637.png)

I don't have this problem on the oracle db.

**Comment by andyjefferson** [comment]
Firstly I don't have SQLServer (and never will have it), consequently it is for people to contribute a "fix" for such issues (made this comment several times on forum and issue tracker for SQLServer and contribs for it are virtually non-existent thus far ... hence it's your opportunity to fill that void ;-)). 

What I can say though is that behaviour of what is the default SQL type for a particular JDBC type is defined in https://github.com/datanucleus/datanucleus-rdbms/blob/master/src/main/java/org/datanucleus/store/rdbms/adapter/SQLServerAdapter.java . It extracts info from the JDBC driver, and attempts to select reasonable defaults. Often JDBC driver's incorrectly declare a type as taking a size when it doesn't and vice versa. All RDBMS have different SQL types. Hence why such things would work on some datastores and not on others. Where I actually have the datastore then such things work, because the XXXAdapter has had updates to support them.

**Comment by nbartels** [comment]
Many thanks for the insights. 

I used the dbinfo to detect the the current varbinary configuration and check the replacement afterwards. The unit test is working again with thi change and so I made a PR (#325) for datanucleus.

**Comment by andyjefferson** [comment]
Fixed by https://github.com/datanucleus/datanucleus-rdbms/commit/cb00fe34fa05c850d3621d94c0bccac8203ba1a1. Thanks for the contrib.

If you have time can you please also do a PR putting the output of Schematool "dbinfo" for SQLServer into https://github.com/datanucleus/datanucleus-rdbms/tree/master/docs. The filename should reflect the version of sqlserver etc, hopefully the current naming scheme is understandable.
