### ISSUE TITLE
Native Sequences with MS SQL Server throws Exception

### ISSUE THREAD

**Issue by benze** [datanucleus/datanucleus-rdbms#363]
When using Datastore Identity with native MS SqlServer Sequence, an exception is thrown b/c the sequence name is wrapped in quotes (') in the `org.datanucleus.store.rdbms.adapter.SQLServerAdapter`; line 651.

Sample test-case attached, and can also be found in forked copy of test-jdo (https://github.com/benze/test-jdo).

Line 651 says: 
```
// Do we need to quote the sequence name here?
StringBuilder stmt = new StringBuilder("SELECT NEXT VALUE FOR '");
stmt.append(sequenceName);
stmt.append("'");
```

When removing the extra quotes in SQLServerAdapter, the sequence works fine.   I have created a PR with the quotes removed (https://github.com/datanucleus/datanucleus-rdbms/pull/364), however I do not know how to run a full suite of tests against the rbdms module to ensure there are no regression bugs.

[test-jdo.zip](https://github.com/datanucleus/datanucleus-rdbms/files/6120346/test-jdo.zip)

**Comment by benze** [comment]
@andyjefferson Thanks for the quick turnaround.  Is there a timeline for the 5.2.7 build to be released?  Are there nightly builds or snapshots produced anywhere I can leverage in the meantime?

**Comment by andyjefferson** [comment]
No timescales available for next release. We used to have nightly builds but they were of limited use compared to the resources required on a server that the project doesn't have expenses for, so it was discontinued. Just do a simple "mvn clean install" on GitHub master and use the generated jar, since that would be identical to what any nightly would provide
